[programs.devnet]
myepicproject = "HQ5tDbxCGvvAdSbsqykXg7Enc1odWVasRCA5xPvyYVaj"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/gilson/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js" 